== Gaffer ==

Gaffer is an open source application framework designed specifically for creating tools for use in visual effects production. It builds on top of the Cortex libraries, adding a flexible node-based computation framework and a user interface framework for editing and viewing node graphs. Gaffer ships with a number of sample modules and applications, not least of which is a module for the on-demand generation of procedural scenes for rendering.

More information can be found on the project homepage: http://imageengine.github.io/gaffer

Developer notes are available on the https://github.com/ImageEngine/gaffer/wiki[project wiki].

=== Downloading ===
Compiled binary releases are available for download from the https://github.com/ImageEngine/gaffer/releases[releases page].

=== Building ===

image:https://travis-ci.org/ImageEngine/gaffer.svg?branch=master["Build Status", link="https://travis-ci.org/ImageEngine/gaffer"]

Gaffer is a fairly large project, and as such has a fairly complex build process. Before you start, you'll want to make sure you have the following prerequisites installed on your system - these will be used to perform the build itself :

- http://www.scons.org[SCons]
- http://www.stack.nl/~dimitri/doxygen/[Doxygen]
- http://inkscape.org[Inkscape]

Gaffer also depends on a number of 3rd party libraries and python modules, many of which are not entirely straightforward to build. We therefore recommend using the latest prebuilt dependencies from https://github.com/johnhaddon/gafferDependencies/releases[the gafferDependencies project]. These are used in our automated test builds and so are guaranteed to be up to date with Gaffer's requirements.

Once you've downloaded the dependencies, you'll want to unpack them and move/rename them to the directory in which you want to make your Gaffer build. We'll refer to this location as `<BUILD_DIR>` in the instructions below - before continuing make sure the dependencies are unpacked as `<BUILD_DIR>/include`, `<BUILD_DIR>/lib` etc.

Next, get yourself a clone of the Gaffer source and change into that directory :

  git clone https://github.com/ImageEngine/gaffer.git
  cd gaffer

You can then build Gaffer itself as follows :

  scons BUILD_DIR=<BUILD_DIR> build

If you encounter any problems, please get in touch via https://groups.google.com/forum/#!forum/gaffer-dev[the developer mailing list] and we'll do our best to help get you up and running.

=== Contributing ===

Contributions to Gaffer are welcome. For small fixes we suggest just going ahead and making a pull request - for anything larger we recommend dicussing it on the https://groups.google.com/forum/#!forum/gaffer-dev[developer list] first, to avoid duplication of effort and to ensure that your whizz-bang ideas fit in with the general direction of the project.

=== Copyright and License ===
© 2013, Image Engine Design Inc. © 2013, John Haddon under https://github.com/ImageEngine/gaffer/blob/master/LICENSE[the BSD license]
