//////////////////////////////////////////////////////////////////////////
//
//	Copyright (c) 2025, John Haddon. All rights reserved.
//
//	Redistribution and use in source and binary forms, with or without
//	modification, are permitted provided that the following conditions are
//	met:
//
//		* Redistributions of source code must retain the above
//		copyright notice, this list of conditions and the following
//		disclaimer.
//
//		* Redistributions in binary form must reproduce the above
//		copyright notice, this list of conditions and the following
//		disclaimer in the documentation and/or other materials provided with
//		the distribution.
//
//		* Neither the name of John Haddon nor the names of
//		any other contributors to this software may be used to endorse or
//		promote products derived from this software without specific prior
//		written permission.
//
//	THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
//	IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
//	THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
//	PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR
//	CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
//	EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
//	PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
//	PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
//	LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
//	NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
//	SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
//////////////////////////////////////////////////////////////////////////

// This file must be installed as `{$FLAMENCO_MANAGER_ROOT}/scripts/gaffer.js`,
// where `$FLAMENCO_MANAGER_ROOT` is the directory which the manager is run
// from.

const JOB_TYPE = {

	label : "Gaffer",
	description : "Runs tasks for Gaffer's FlamencoDispatcher node.",
	settings : [
		{
			key: "tasks",
			type: "list",
			default : [],
			description : "The task definitions generated by the FlamencoDispatcher node.",
		},
	],
};

function compileJob( job ) {

	let tasks = {};

	for( const taskDefinition of job.settings.tasks ) {

		const task = author.Task( taskDefinition["name"], "misc" );
		tasks[taskDefinition["id"]] = task;

		if( "commandArgs" in taskDefinition )
		{
			const command = author.Command(
				"exec",
				{
					exe : process.platform === "windows" ? "gaffer.cmd" : "gaffer",
					args : taskDefinition["commandArgs"],
				}
			);
			task.addCommand( command );
		}

		if( "dependencies" in taskDefinition )
		{
			for( const taskID of taskDefinition["dependencies"] )
			{
				task.addDependency( tasks[taskID] );
			}
		}

		job.addTask( task );

		// The `tasks` field isn't really human readable - remove it
		// so it doesn't clutter the web UI.

		delete job.settings["tasks"];

	}
}
