#!/usr/bin/env python

import os,sys

build_root = os.getcwd()

gp_cmd = 'gaffer python'
ad_cmd = 'asciidoc'
ag_cmd = 'gaffer screenGrabber'
pdf_cmd = '/home/btoogood/Tools/wkhtmltopdf-amd64'


#build the node reference
os.chdir( os.path.join (build_root, 'GafferNodeReference' ))

## extract the info from the node metadata
os.system( gp_cmd + " extractoMatic.py" )

## run asciidoc then convert the result into a pdf
os.system( ad_cmd + " GafferNodeReference.txt" )
os.system( pdf_cmd + " GafferNodeReference.html GafferNodeReference.pdf" )



#build the user guide
os.chdir( os.path.join( build_root, 'GafferUserGuide' ))

##generate images from reference scripts
source_dir = os.path.join( build_root, 'GafferUserGuide', 'images', 'autoGenerated_source' )
target_dir = os.path.join( build_root, 'GafferUserGuide', 'images', 'autoGenerated_target' )
for source in os.listdir( source_dir ):
    print( "Processing [ %s ]" % ( source ) )
    target_img = source[:-4] + ".png"
    ag_cmd_full = "%s -source %s -image %s" % \
                  (ag_cmd, os.path.join( source_dir, source ), os.path.join( target_dir, target_img ) )
    print( ag_cmd_full )

## run asciidoc then convert the result into a pdf
os.system( ad_cmd + " GafferUserGuide.txt" )
os.system( pdf_cmd + " GafferUserGuide.html GafferUserGuide.pdf" )

