#!/bin/bash

export GAFFER_OPTIONS_FILE=

export DELIGHT='/software/apps/3delight/10.0.49/cent6.x86_64'
export ARNOLD_ROOT='/software/apps/arnold/4.1.2.0/cent6.x86_64'

export PATH=/software/apps/scons/2.0.1/bin/:/software/apps/cmake/2.8.4/cent6.x86_64/bin:/software/apps/doxygen/1.8.4/cent6.x86_64/bin:/usr/local/bin:/usr/bin:/bin

export LD_LIBRARY_PATH=/software/apps/python/2.7/cent6.x86_64/gcc/4.1.2/lib

pushd . &> /dev/null

cd `dirname $0`
cd ..
releaseScript=`pwd`/release/release.py

popd &> /dev/null

/software/apps/python/2.7/cent6.x86_64/gcc/4.1.2/bin/python $releaseScript "$@"
